from __future__ import annotations

from .models import normalize_coverage_county_name, normalize_coverage_state_code


SUPPORTED_DRILLER_GEOGRAPHY: dict[str, dict[str, object]] = {
    "TX": {
        "name": "Texas",
        "counties": [
            "Anderson",
            "Andrews",
            "Angelina",
            "Aransas",
            "Archer",
            "Armstrong",
            "Atascosa",
            "Austin",
            "Bailey",
            "Bandera",
            "Bastrop",
            "Baylor",
            "Bee",
            "Bell",
            "Bexar",
            "Blanco",
            "Borden",
            "Bosque",
            "Bowie",
            "Brazoria",
            "Brazos",
            "Brewster",
            "Briscoe",
            "Brooks",
            "Brown",
            "Burleson",
            "Burnet",
            "Caldwell",
            "Calhoun",
            "Callahan",
            "Cameron",
            "Camp",
            "Carson",
            "Cass",
            "Castro",
            "Chambers",
            "Cherokee",
            "Childress",
            "Clay",
            "Cochran",
            "Coke",
            "Coleman",
            "Collin",
            "Collingsworth",
            "Colorado",
            "Comal",
            "Comanche",
            "Concho",
            "Cooke",
            "Coryell",
            "Cottle",
            "Crane",
            "Crockett",
            "Crosby",
            "Culberson",
            "Dallam",
            "Dallas",
            "Dawson",
            "Deaf Smith",
            "Delta",
            "Denton",
            "DeWitt",
            "Dickens",
            "Dimmit",
            "Donley",
            "Duval",
            "Eastland",
            "Ector",
            "Edwards",
            "Ellis",
            "El Paso",
            "Erath",
            "Falls",
            "Fannin",
            "Fayette",
            "Fisher",
            "Floyd",
            "Foard",
            "Fort Bend",
            "Franklin",
            "Freestone",
            "Frio",
            "Gaines",
            "Galveston",
            "Garza",
            "Gillespie",
            "Glasscock",
            "Goliad",
            "Gonzales",
            "Gray",
            "Grayson",
            "Gregg",
            "Grimes",
            "Guadalupe",
            "Hale",
            "Hall",
            "Hamilton",
            "Hansford",
            "Hardeman",
            "Hardin",
            "Harris",
            "Harrison",
            "Hartley",
            "Haskell",
            "Hays",
            "Hemphill",
            "Henderson",
            "Hidalgo",
            "Hill",
            "Hockley",
            "Hood",
            "Hopkins",
            "Houston",
            "Howard",
            "Hudspeth",
            "Hunt",
            "Hutchinson",
            "Irion",
            "Jack",
            "Jackson",
            "Jasper",
            "Jeff Davis",
            "Jefferson",
            "Jim Hogg",
            "Jim Wells",
            "Johnson",
            "Jones",
            "Karnes",
            "Kaufman",
            "Kendall",
            "Kenedy",
            "Kent",
            "Kerr",
            "Kimble",
            "King",
            "Kinney",
            "Kleberg",
            "Knox",
            "Lamar",
            "Lamb",
            "Lampasas",
            "LaSalle",
            "Lavaca",
            "Lee",
            "Leon",
            "Liberty",
            "Limestone",
            "Lipscomb",
            "Live Oak",
            "Llano",
            "Loving",
            "Lubbock",
            "Lynn",
            "Madison",
            "Marion",
            "Martin",
            "Mason",
            "Matagorda",
            "Maverick",
            "McCulloch",
            "McLennan",
            "McMullen",
            "Medina",
            "Menard",
            "Midland",
            "Milam",
            "Mills",
            "Mitchell",
            "Montague",
            "Montgomery",
            "Moore",
            "Morris",
            "Motley",
            "Nacogdoches",
            "Navarro",
            "Newton",
            "Nolan",
            "Nueces",
            "Ochiltree",
            "Oldham",
            "Orange",
            "Palo Pinto",
            "Panola",
            "Parker",
            "Parmer",
            "Pecos",
            "Polk",
            "Potter",
            "Presidio",
            "Rains",
            "Randall",
            "Reagan",
            "Real",
            "Red River",
            "Reeves",
            "Refugio",
            "Roberts",
            "Robertson",
            "Rockwall",
            "Runnels",
            "Rusk",
            "Sabine",
            "San Augustine",
            "San Jacinto",
            "San Patricio",
            "San Saba",
            "Schleicher",
            "Scurry",
            "Shackelford",
            "Shelby",
            "Sherman",
            "Smith",
            "Somervell",
            "Starr",
            "Stephens",
            "Sterling",
            "Stonewall",
            "Sutton",
            "Swisher",
            "Tarrant",
            "Taylor",
            "Terrell",
            "Terry",
            "Throckmorton",
            "Titus",
            "Tom Green",
            "Travis",
            "Trinity",
            "Tyler",
            "Upshur",
            "Upton",
            "Uvalde",
            "Val Verde",
            "Van Zandt",
            "Victoria",
            "Walker",
            "Waller",
            "Ward",
            "Washington",
            "Webb",
            "Wharton",
            "Wheeler",
            "Wichita",
            "Wilbarger",
            "Willacy",
            "Williamson",
            "Wilson",
            "Winkler",
            "Wise",
            "Wood",
            "Yoakum",
            "Young",
            "Zapata",
            "Zavala",
        ],
    }
}

DEFAULT_DRILLER_STATE_CODE = "TX"


def supported_state_codes() -> list[str]:
    return sorted(SUPPORTED_DRILLER_GEOGRAPHY.keys())


def supported_states_payload() -> list[dict]:
    items: list[dict] = []
    for state_code in supported_state_codes():
        definition = SUPPORTED_DRILLER_GEOGRAPHY[state_code]
        counties = list(definition.get("counties") or [])
        items.append(
            {
                "state_code": state_code,
                "name": str(definition.get("name") or state_code),
                "county_count": len(counties),
                "counties": counties,
            }
        )
    return items


def ensure_supported_state(state_code: str | None) -> str:
    normalized_state = normalize_coverage_state_code(state_code)
    if normalized_state not in SUPPORTED_DRILLER_GEOGRAPHY:
        raise ValueError(f"{normalized_state} is not currently supported in driller settings.")
    return normalized_state


def ensure_supported_counties(*, state_code: str | None, county_names: list[str] | tuple[str, ...]) -> list[str]:
    normalized_state = ensure_supported_state(state_code)
    supported_counties = {
        normalize_coverage_county_name(item): item
        for item in list(SUPPORTED_DRILLER_GEOGRAPHY[normalized_state].get("counties") or [])
    }
    normalized_counties: list[str] = []
    seen: set[str] = set()
    for county_name in county_names:
        normalized = normalize_coverage_county_name(county_name)
        if not normalized:
            continue
        if normalized not in supported_counties:
            raise ValueError(f"{normalized} is not currently supported for {normalized_state}.")
        if normalized in seen:
            continue
        normalized_counties.append(supported_counties[normalized])
        seen.add(normalized)
    return normalized_counties
